import {
    StyleSheet
}
from 'react-native';

const Styles = StyleSheet.create({
    categoryWrap:{
       
    },
    categoryText:{
        fontWeight:'bold',
        fontSize:17,
        textAlign:'center',
        marginTop:10
    },
    img:{
        width:70,
        height:70
    },
    categoryIcon:{
        flexDirection:'row',
        justifyContent:'center',
        width:'96%',
        alignSelf:'center',
        borderWidth:StyleSheet.hairlineWidth,
        borderColor:'gray',
        borderStyle:'dashed',
        marginTop:10
    },
    itemCategory:{
        width:'50%',
        alignItems:'center',
        borderWidth:StyleSheet.hairlineWidth,
        borderColor:'gray',
        borderStyle:'dashed',
        paddingTop:10,
        paddingBottom:10,
    },
    bartool:{
        flexDirection:'row'
    },
    merchantWrap:{
        width:'95%',
        alignSelf:'center'
    },
    cancelText:{
        fontWeight:'bold',
        fontSize:20
    },
    cancel:{
        width:'10%'
    },
    title:{
        width:'90%',
        textAlign:'center',
        fontSize:20,
        fontWeight:'bold'
    },
    //Detail merchant
    detailWrap:{
        width:'95%',
        alignSelf:'center'
    },
    inforMerhant:{
        backgroundColor:'white',
        paddingTop:30,
        paddingBottom:30,
        borderRadius:10,
        shadowOpacity:1,
        marginTop:20,
        justifyContent:'center',
        alignItems:'center'
    },
    nameMerchant:{
        fontWeight:'bold',
        fontSize:23
    },
    address:{
        opacity:0.7
    },
    menu:{
        height:'73%'
    },
    menuFull:{
        height:'80%'
    },
    header:{
        height:'20%'
    },
    btnCart:{
        height:'7%'
    },
    textMenu:{
        fontWeight:'bold',
        fontSize:20
    }
});
export default Styles;